apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mini-modern-cluster
  region: us-east-1
  version: "1.32"

iam:
  serviceRoleARN: arn:aws:iam::834701024565:role/EKSControlPlaneRole-311091.13461756564577

nodeGroups:
  - name: ng-group
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    iam:
      instanceRoleARN: arn:aws:iam::834701024565:role/EKSNodeInstanceRole-311091.13461756564577
      instanceProfileARN: arn:aws:iam::834701024565:instance-profile/EKSNodeInstanceProfile

